#ifndef __STRUCTURES__H
#define __STRUCTURES__H

#include <windivert.h>

typedef struct
{
    WINDIVERT_IPHDR  ip;
    WINDIVERT_TCPHDR tcp;
} PACKET, *PPACKET;

typedef struct 
{
    PACKET header;
    UINT8 data[];
	//UINT8* data;
} DATAPACKET, *PDATAPACKET;

void PacketInit(PPACKET packet);
//{
//	memset(packet, 0, sizeof(PACKET));
//	packet->ip.Version = 4;
//	packet->ip.HdrLength = sizeof(WINDIVERT_IPHDR) / sizeof(UINT32);
//	packet->ip.Length = htons(sizeof(PACKET));
//	packet->ip.TTL = 64;
//	packet->ip.Protocol = IPPROTO_TCP;
//	packet->tcp.HdrLength = sizeof(WINDIVERT_TCPHDR) / sizeof(UINT32);
//	//packet->tcp.Rst = 1;
//	//packet->tcp.Ack = 1;
//}

#define MAXBUF 0XFFFF

const char block_data[] = 
	"HTTP/1.1 400 Bad Request\r\n"
	"Server: CloudFront\r\n"
	"Date: Sat, 30 Sep 2017 08:06:51 GMT\r\n"
	"Content-Type: text/html\r\n"
	"Content-Length: 551\r\n"
	"Connection: close\r\n"
	"X-Cache: Error from cloudfront\r\n"
	"Via: 1.1 c6d88d36c0be0174a24748de08dfae6b.cloudfront.net (CloudFront)\r\n"
	"X-Amz-Cf-Id: K4vqVxFPID7WYDTwsOBUc72KJYMVkhnH1vYj-2YpikNKT6ewp3il0w==\r\n\r\n"
	"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">"
	"<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">"
	"<TITLE>ERROR: The request could not be satisfied</TITLE>"
	"</HEAD><BODY>"
	"<H1>ERROR</H1>"
	"<H2>The request could not be satisfied.</H2>"
	"<HR noshade size=\"1px\">"
	"Bad request."
	"<BR clear=\"all\">"
	"<HR noshade size=\"1px\">"
	"<PRE>"
	"Generated by cloudfront (CloudFront)"
	"Request ID: K4vqVxFPID7WYDTwsOBUc72KJYMVkhnH1vYj-2YpikNKT6ewp3il0w=="
	"</PRE>"
	"<ADDRESS>"
	"</ADDRESS>"
	"</BODY></HTML>";
#endif//__STRUCTURES__H
